server {
    listen 80;
    server_name pickle.nandharu.uk;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        limit_req zone=general burst=20 nodelay;
        proxy_pass http://pickleball:3000;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $http_cf_connecting_ip;
        proxy_set_header X-Forwarded-For   $http_cf_connecting_ip;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
